### PR TITLE
Update okta.mdx

### PR DESCRIPTION
**Pull request by mikemaxey**
### Description
Please describe your pull request.

💔Thank you!

### CODE REVIEW

**Comment by mikemaxey** [comment]
Don't pull yet, need to update a few things. thx

**Comment by mikemaxey** [comment]
Ready for review

**Review by tashian — APPROVED** [review]
lgtm.

(I added some cosmetics / grammatical tweaks)

**Comment by tashian** [comment]
**Note**: smallstep/web#615 needs to be deployed alongside this PR.

**Review by dopey — APPROVED** [review]
lgtm

**Pull request merged**
